In [1]:
import os
import joblib
import numpy as np
import matplotlib.pyplot as plt


Bad key text.latex.preview in file C:\Users\Abhinav\anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle, line 123 ('text.latex.preview : False')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.5.0/matplotlibrc.template
or from the matplotlib source distribution

Bad key mathtext.fallback_to_cm in file C:\Users\Abhinav\anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle, line 155 ('mathtext.fallback_to_cm : True  # When True, use symbols from the Computer Modern')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.5.0/matplotlibrc.template
or from the matplotlib source distribution

Bad key savefig.jpeg_quality in file C:\Users\Abhinav\anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle, line 418 ('savefig.jpeg_quality: 95       # when a jpeg is saved, the default quality parameter.')
You

In [2]:
plt.style.use("fivethirtyeight")

In [10]:
class Perceptron:
    def __init__(self, eta: float=None, epochs: int=None):
        self.weights = np.random.randn(3) * 1e-4
        self.eta = eta # learning rate
        self.epochs = epochs # iterations
        
    def activation_function(self,z):
        return np.where(z > 0, 1, 0)
        
    def _z_outcome(self,inputs,weights):
        return np.dot(inputs,weights)
        
    def fit(self, X, y):
        self.X = X
        self.y = y
        
        X_with_bias = np.c_[self.X, -np.ones((len(self.X), 1))]
        print(f"X with bias: \n{X_with_bias}")
        
        for epoch in range(self.epochs):
            print("--"*10)
            print(f"f for epochs >> {epoch + 1}")
            print("--"*10)
            z = self._z_outcome(X_with_bias,self.weights)
            y_hat = self.activation_function(z)
            print(f"Predicted values after forward pass: \n{y_hat}")
            
            self.error = self.y- y_hat
            print(f"error: \n{self.error}")
            
            self.weights = self.weights + self.eta * np.dot(X_with_bias.T , self.error)
            print(f"updated weights after epochs: {epoch + 1}/{self.epochs} : \n{self.weights}")
            print(f"##"*10)
    
    def predict(self,X):
        X_with_bias = np.c_[X, -np.ones((len(X), 1))]
        z = self._z_outcome(X_with_bias, self.weights)
        return self.activation_function(z)
            
   
        

In [11]:
import pandas as pd

In [12]:
OR = {
    "x1" : [0,0,1,1],
    "x2" : [0,1,0,1],
    "y" : [0,1,1,1]
}

df_OR = pd.DataFrame(OR)
df_OR

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [13]:
def prepare_data(df,target_col = "y"):
    X = df.drop(target_col,axis = 1)
    y = df[target_col]
    return X,y

In [14]:
X,y = prepare_data(df_OR)

ETA = 0.1
EPOCHS = 10

model_or = Perceptron(eta = ETA,epochs = EPOCHS)

In [15]:
model_or.fit(X,y)

X with bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
f for epochs >> 1
--------------------
Predicted values after forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epochs: 1/10 : 
[ 3.06481369e-05 -2.65634517e-05  9.99526750e-02]
####################
--------------------
f for epochs >> 2
--------------------
Predicted values after forward pass: 
[0 0 0 0]
error: 
0    0
1    1
2    1
3    1
Name: y, dtype: int64
updated weights after epochs: 2/10 : 
[ 0.20003065  0.19997344 -0.20004732]
####################
--------------------
f for epochs >> 3
--------------------
Predicted values after forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epochs: 3/10 : 
[ 0.20003065  0.19997344 -0.10004732]
####################
--------------------
f for epochs >> 4
--------------------
Predicted values after forward pass: 
[1 1 1 1]
error: 
0   -1
1

In [16]:
model_or.predict(X = [[1,1]])

array([1])

In [23]:
XOR = {
    "x1" : [0,0,1,1],
    "x2" : [0,1,0,1],
    "y" : [0,1,1,0]
}

df_XOR = pd.DataFrame(XOR)
df_XOR

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  0

In [25]:
XOR = {
    "x1" : [0,0,1,1],
    "x2" : [0,1,0,1],
    "y" : [0,1,1,0]
}

df_XOR = pd.DataFrame(XOR)
df_XOR
X,y = prepare_data(df_AND)

ETA = 0.1
EPOCHS = 10

model_and = Perceptron(eta = ETA,epochs = EPOCHS)
model_and.fit(X,y)

X with bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
f for epochs >> 1
--------------------
Predicted values after forward pass: 
[1 0 1 0]
error: 
0   -1
1    1
2    0
3    0
Name: y, dtype: int64
updated weights after epochs: 1/10 : 
[ 2.82123368e-05  9.99179235e-02 -4.50219874e-05]
####################
--------------------
f for epochs >> 2
--------------------
Predicted values after forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights after epochs: 2/10 : 
[-9.99717877e-02 -8.20764894e-05  1.99954978e-01]
####################
--------------------
f for epochs >> 3
--------------------
Predicted values after forward pass: 
[0 0 0 0]
error: 
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights after epochs: 3/10 : 
[ 2.82123368e-05  9.99179235e-02 -4.50219874e-05]
####################
--------------------
f for epochs >> 4
--------------------
Predicted values after forward pass: 
[1